// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v7.36.1
// source: dashboard.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "dashboard_backend";

export interface Dashboard {
  presence?: Presence | undefined;
  light?: Light | undefined;
  weather?: Weather | undefined;
  phone?: Phone | undefined;
  todosit?: Todoist | undefined;
}

export interface Presence {
  isNow?: boolean | undefined;
  lastSeen?: number | undefined;
}

export interface Light {
  luxValue?: number | undefined;
  isLight?: boolean | undefined;
}

export interface Weather {
  /** TODO: update */
  degrees?: number | undefined;
}

export interface Phone {
  steps?: number | undefined;
}

export interface Todoist {
  task: Task[];
}

/** TODO: */
export interface Task {
}

function createBaseDashboard(): Dashboard {
  return { presence: undefined, light: undefined, weather: undefined, phone: undefined, todosit: undefined };
}

export const Dashboard: MessageFns<Dashboard> = {
  encode(message: Dashboard, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.presence !== undefined) {
      Presence.encode(message.presence, writer.uint32(10).fork()).join();
    }
    if (message.light !== undefined) {
      Light.encode(message.light, writer.uint32(18).fork()).join();
    }
    if (message.weather !== undefined) {
      Weather.encode(message.weather, writer.uint32(26).fork()).join();
    }
    if (message.phone !== undefined) {
      Phone.encode(message.phone, writer.uint32(34).fork()).join();
    }
    if (message.todosit !== undefined) {
      Todoist.encode(message.todosit, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Dashboard {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseDashboard();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.presence = Presence.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.light = Light.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.weather = Weather.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.phone = Phone.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.todosit = Todoist.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Dashboard {
    return {
      presence: isSet(object.presence) ? Presence.fromJSON(object.presence) : undefined,
      light: isSet(object.light) ? Light.fromJSON(object.light) : undefined,
      weather: isSet(object.weather) ? Weather.fromJSON(object.weather) : undefined,
      phone: isSet(object.phone) ? Phone.fromJSON(object.phone) : undefined,
      todosit: isSet(object.todosit) ? Todoist.fromJSON(object.todosit) : undefined,
    };
  },

  toJSON(message: Dashboard): unknown {
    const obj: any = {};
    if (message.presence !== undefined) {
      obj.presence = Presence.toJSON(message.presence);
    }
    if (message.light !== undefined) {
      obj.light = Light.toJSON(message.light);
    }
    if (message.weather !== undefined) {
      obj.weather = Weather.toJSON(message.weather);
    }
    if (message.phone !== undefined) {
      obj.phone = Phone.toJSON(message.phone);
    }
    if (message.todosit !== undefined) {
      obj.todosit = Todoist.toJSON(message.todosit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Dashboard>, I>>(base?: I): Dashboard {
    return Dashboard.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Dashboard>, I>>(object: I): Dashboard {
    const message = createBaseDashboard();
    message.presence = (object.presence !== undefined && object.presence !== null)
      ? Presence.fromPartial(object.presence)
      : undefined;
    message.light = (object.light !== undefined && object.light !== null) ? Light.fromPartial(object.light) : undefined;
    message.weather = (object.weather !== undefined && object.weather !== null)
      ? Weather.fromPartial(object.weather)
      : undefined;
    message.phone = (object.phone !== undefined && object.phone !== null) ? Phone.fromPartial(object.phone) : undefined;
    message.todosit = (object.todosit !== undefined && object.todosit !== null)
      ? Todoist.fromPartial(object.todosit)
      : undefined;
    return message;
  },
};

function createBasePresence(): Presence {
  return { isNow: undefined, lastSeen: undefined };
}

export const Presence: MessageFns<Presence> = {
  encode(message: Presence, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isNow !== undefined) {
      writer.uint32(8).bool(message.isNow);
    }
    if (message.lastSeen !== undefined) {
      writer.uint32(16).uint64(message.lastSeen);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Presence {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePresence();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.isNow = reader.bool();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.lastSeen = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Presence {
    return {
      isNow: isSet(object.isNow)
        ? globalThis.Boolean(object.isNow)
        : isSet(object.is_now)
        ? globalThis.Boolean(object.is_now)
        : undefined,
      lastSeen: isSet(object.lastSeen)
        ? globalThis.Number(object.lastSeen)
        : isSet(object.last_seen)
        ? globalThis.Number(object.last_seen)
        : undefined,
    };
  },

  toJSON(message: Presence): unknown {
    const obj: any = {};
    if (message.isNow !== undefined) {
      obj.isNow = message.isNow;
    }
    if (message.lastSeen !== undefined) {
      obj.lastSeen = Math.round(message.lastSeen);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Presence>, I>>(base?: I): Presence {
    return Presence.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Presence>, I>>(object: I): Presence {
    const message = createBasePresence();
    message.isNow = object.isNow ?? undefined;
    message.lastSeen = object.lastSeen ?? undefined;
    return message;
  },
};

function createBaseLight(): Light {
  return { luxValue: undefined, isLight: undefined };
}

export const Light: MessageFns<Light> = {
  encode(message: Light, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.luxValue !== undefined) {
      writer.uint32(8).int32(message.luxValue);
    }
    if (message.isLight !== undefined) {
      writer.uint32(16).bool(message.isLight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Light {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLight();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.luxValue = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.isLight = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Light {
    return {
      luxValue: isSet(object.luxValue)
        ? globalThis.Number(object.luxValue)
        : isSet(object.lux_value)
        ? globalThis.Number(object.lux_value)
        : undefined,
      isLight: isSet(object.isLight)
        ? globalThis.Boolean(object.isLight)
        : isSet(object.is_light)
        ? globalThis.Boolean(object.is_light)
        : undefined,
    };
  },

  toJSON(message: Light): unknown {
    const obj: any = {};
    if (message.luxValue !== undefined) {
      obj.luxValue = Math.round(message.luxValue);
    }
    if (message.isLight !== undefined) {
      obj.isLight = message.isLight;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Light>, I>>(base?: I): Light {
    return Light.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Light>, I>>(object: I): Light {
    const message = createBaseLight();
    message.luxValue = object.luxValue ?? undefined;
    message.isLight = object.isLight ?? undefined;
    return message;
  },
};

function createBaseWeather(): Weather {
  return { degrees: undefined };
}

export const Weather: MessageFns<Weather> = {
  encode(message: Weather, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.degrees !== undefined) {
      writer.uint32(8).int32(message.degrees);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Weather {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseWeather();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.degrees = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Weather {
    return { degrees: isSet(object.degrees) ? globalThis.Number(object.degrees) : undefined };
  },

  toJSON(message: Weather): unknown {
    const obj: any = {};
    if (message.degrees !== undefined) {
      obj.degrees = Math.round(message.degrees);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Weather>, I>>(base?: I): Weather {
    return Weather.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Weather>, I>>(object: I): Weather {
    const message = createBaseWeather();
    message.degrees = object.degrees ?? undefined;
    return message;
  },
};

function createBasePhone(): Phone {
  return { steps: undefined };
}

export const Phone: MessageFns<Phone> = {
  encode(message: Phone, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.steps !== undefined) {
      writer.uint32(8).int32(message.steps);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Phone {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePhone();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.steps = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Phone {
    return { steps: isSet(object.steps) ? globalThis.Number(object.steps) : undefined };
  },

  toJSON(message: Phone): unknown {
    const obj: any = {};
    if (message.steps !== undefined) {
      obj.steps = Math.round(message.steps);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Phone>, I>>(base?: I): Phone {
    return Phone.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Phone>, I>>(object: I): Phone {
    const message = createBasePhone();
    message.steps = object.steps ?? undefined;
    return message;
  },
};

function createBaseTodoist(): Todoist {
  return { task: [] };
}

export const Todoist: MessageFns<Todoist> = {
  encode(message: Todoist, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.task) {
      Task.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Todoist {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTodoist();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.task.push(Task.decode(reader, reader.uint32()));
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Todoist {
    return { task: globalThis.Array.isArray(object?.task) ? object.task.map((e: any) => Task.fromJSON(e)) : [] };
  },

  toJSON(message: Todoist): unknown {
    const obj: any = {};
    if (message.task?.length) {
      obj.task = message.task.map((e) => Task.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Todoist>, I>>(base?: I): Todoist {
    return Todoist.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Todoist>, I>>(object: I): Todoist {
    const message = createBaseTodoist();
    message.task = object.task?.map((e) => Task.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTask(): Task {
  return {};
}

export const Task: MessageFns<Task> = {
  encode(_: Task, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Task {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTask();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): Task {
    return {};
  },

  toJSON(_: Task): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Task>, I>>(base?: I): Task {
    return Task.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Task>, I>>(_: I): Task {
    const message = createBaseTask();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
